### ISSUE TITLE
'Method '_add from Integer' was called on Null' error on launch of the app

### ISSUE THREAD

**Issue by emvaized** [tp7309/flutter_sticky_and_expandable_list#2]
This error occurs on every launch of the app, even if there's no `SliverExpandableList` widget built on the screen.

![Screenshot_20200316_181606](https://user-images.githubusercontent.com/37851576/76788412-8bcd6980-67c3-11ea-840e-f367149fa121.png)

Here's the log:
```
I/flutter ( 5599): The method '_addFromInteger' was called on null.
I/flutter ( 5599): Receiver: null
I/flutter ( 5599): Tried calling: _addFromInteger(1)
I/flutter ( 5599): 
I/flutter ( 5599): The relevant error-causing widget was:
I/flutter ( 5599):   Feed-[LabeledGlobalKey<FeedState>#fb6be]
I/flutter ( 5599):   file:///home/max/%D0%9A%D0%BE%D0%B4/Flutter%20Projects/Feed-master/lib/main.dart:257:15
I/flutter ( 5599): 
I/flutter ( 5599): When the exception was thrown, this was the stack:
I/flutter ( 5599): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter ( 5599): #1      int.+ (dart:core-patch/integers.dart:12:38)
I/flutter ( 5599): #2      SliverExpandableChildDelegate._buildSectionRealIndexes (package:sticky_and_expandable_list/src/sliver_expandable_list.dart:168:22)
I/flutter ( 5599): #3      new SliverExpandableChildDelegate (package:sticky_and_expandable_list/src/sliver_expandable_list.dart:69:30)
```

**Comment by tp7309** [comment]
Ensure all section object in **sectionList** is not null.
try `flutter clean` , then run your project again.

**Comment by emvaized** [comment]
> Ensure all section object in **sectionList** is not null.
> try `flutter clean` , then run your project again.

Works now! :+1:
